[phases.setup]
nixPkgs = ["python311", "opencv", "ffmpeg"]

[phases.install]
cmds = [
    "python -m pip install -r backend/requirements.txt"
]

[phases.build]
cmds = [
    "echo 'GymJam AI WebRTC Build complete'"
]

[start]
cmd = "cd backend && python app_webrtc.py"
